### ISSUE TITLE
Firestore sample structure for the example provided on the repository.

### ISSUE THREAD

**Issue by haizadvnet** [zeshuaro/firestore_cache#123]
Hi, I am following the example code and I am trying to fetch lists under posts collection. Can you help me on this? 

```
  Future<QuerySnapshot<Map<String, dynamic>>> _getDocs() async {

    const cacheField = 'updatedAt';
    final cacheDocRef = _firestore.doc('status/status');
    final query = _firestore.collection('posts');

    final snapshot = await FirestoreCache.getDocuments(
      query: query,
      cacheDocRef: cacheDocRef,
      firestoreCacheField: cacheField,
    );

   print(snapshot.docs); 
    return snapshot;
  }
```

I am getting no list under the `snapshot.docs`.

Firestore Panel view
![image](https://user-images.githubusercontent.com/85096754/222688558-4e4469af-b36f-4fb5-b52e-c508d8ac8ed1.png)

query builder
 ![image](https://user-images.githubusercontent.com/85096754/222688114-60552d93-cb37-4dbf-8179-84848d382b6a.png)

I am very appreciated if you can provide the data structure on the Firestore for the example provided on this repository.

Thank you for your time.

**Comment by zeshuaro** [comment]
Hey @haizadvnet, the example code assumes you have set up your data structure as follows instead:

![image](https://user-images.githubusercontent.com/12210067/222897940-1b1eb62d-dff6-4c0a-a360-b714f3834a93.png)

![image](https://user-images.githubusercontent.com/12210067/222897986-b221c8fc-ef1d-44e8-8789-f520e5a975ca.png)

Hope it helps!

**Comment by haizadvnet** [comment]
Hey @zeshuaro , thanks for your help. The code are working fine.

I have a concern on the number of Firestore reads. By following the example code below, all data of userId are returning `isFromCache: false` whenever I updated the  `updatedAt` field on Firestore to the newest timestamp. What I did was only update a postId through firestore panel, and then change the `updatedAt` value.

I thought only one postId will return `isFromCache: false`, not other postId are affected. :thinking: I am afraid that it will makes the Firestore reads to be costly later on.

```
  Widget _buildDoc() {
    return FutureBuilder<DocumentSnapshot>(
      future: _futureDoc,
      builder: (context, snapshot) {
        if (snapshot.hasError) {
          return Text('${snapshot.error}');
        } else if (snapshot.hasData) {
          final doc = snapshot.data!;
          final data = doc.data() as Map?;

          return Text(
            '${data!['userId']} isFromCache: ${doc.metadata.isFromCache}',
          );
        }

        return const CircularProgressIndicator();
      },
    );
  }
```

**Comment by zeshuaro** [comment]
To optimise the use of caching, you should use different cache documents for different collections. For example, you should store the timestamp under `status/postsStatus` for the `posts` collection, and store another timestamp under `status/usersStatus` for the `users` collection.

> I thought only one postId will return isFromCache: false, not other postId are affected. 🤔 I am afraid that it will makes the Firestore reads to be costly later on.

This package does not offer this capability, unfortunately. The idea behind this package is to simply cache the querying a list of documents from a collection. When this cache is invalidated by the `updatedAt` timestamp, there is no cheap way to determine which document needs to be updated and which doesn't. So it will have to run the whole query again to get the latest data.

**Comment by haizadvnet** [comment]
Well noted sir, thanks for your clarification 👍
