### ISSUE TITLE
Make it support realtime-database

### ISSUE THREAD

**Issue by sparkmobi** [zeshuaro/firestore_cache#20]
hello,

please add the support of real-time database package also

**Comment by zeshuaro** [comment]
I believe the Firebase Realtime Database package already allows you to persist data which is documented [here](https://pub.dev/documentation/firebase_database/latest/firebase_database/FirebaseDatabase/setPersistenceEnabled.html).

**Comment by zeshuaro** [comment]
I'm aware that this has taken a lot longer than I expected but it's finally here, see [firebase_db_cache](https://pub.dev/packages/firebase_db_cache) for support of Firebase Realtime Database.
