### ISSUE TITLE
It is not clear from description if it saves money or no

### ISSUE THREAD

**Issue by totalerex** [zeshuaro/firestore_cache#21]
Hi! 

Could you please add to the description some explanation how it saves reads from firestore.

**Comment by bartektartanus** [comment]
Hi @totalerex! I'm not the maintainer of this package, but after some code reading I think that this package does not save money. At least for reading single documents. Maybe for queries where you return more then one document.

**Comment by zeshuaro** [comment]
I haven't done any benchmarking on pricing and only did some basic observations of the number of reads. From the observations, it does reduce the number of reads on Firestore. Feel free to share your usage and experience.

**Comment by gOzaru** [comment]
Basically, if you want to reduce amount of reads, then you should put all fields into variable Map inside Firestore and separate them based on the use case. After doing that and combined with this package, it is worth saving a lot of money if your database doesn't always update its data every time. 

For example, you want to create a music app which is stored on online cloud. 
We can only update data if new Musician joins in to our app and upload all of their songs to database. And therefore this is a money-saving procedure.
