### ISSUE TITLE
cloud_firestore 0.14.0

### ISSUE THREAD

**Issue by flutterfrank** [zeshuaro/firestore_cache#22]
firestore_cache 0.1.1 does not work with cloud_firestore 0.14.0 .

**Comment by zeshuaro** [comment]
`cloud_firestore` 0.14.0 introduced a lot of breaking changes. I'm using another package to mock `cloud_firestore` for testing so I'll have to wait for that package to update before updating `firestore_cache`.

**Comment by allanwolski** [comment]
Waiting for this too.

**Comment by zeshuaro** [comment]
`firestore_cache 0.2.0` has been updated to support `cloud_firestore >= 0.14.0`
