### ISSUE TITLE
Nullsafety

### ISSUE THREAD

**Issue by jeremylingg** [zeshuaro/firestore_cache#34]
Would be great if you could support nullsafety and Flutter 2.0

**Comment by zeshuaro** [comment]
Yup, waiting for the mocking package to be updated before I update this one 🙂

**Comment by AathifMahir** [comment]
@zeshuaro Is there any ETA for Firestore 1.0 support?

It would be great, if we have the new version within next couple of days.

**Comment by zeshuaro** [comment]
Let me have a look if I can drop the mocking package dependency because that's the blocker at the moment, waiting for that package to be updated. If I can drop that dependency, then maybe I can update it to support `cloud_firestore 1.0` sooner.

**Comment by AathifMahir** [comment]
looking forward for new update on this module

**Comment by AathifMahir** [comment]
@zeshuaro Any Eta for Null Safety version with Flutter 2.0 support? I have been waiting for a while now for this package

**Comment by zeshuaro** [comment]
`cloud_firestore` has just been updated to address an issue preventing the mocking package to work. I'm making changes to the package now to support null-safety. Should be able to release a new version by end of the week latest.

**Comment by AathifMahir** [comment]
> `cloud_firestore` has just been updated to address an issue preventing the mocking package to work. I'm making changes to the package now to support null-safety. Should be able to release a new version by end of the week latest.

Sure, Thanks
