### ISSUE TITLE
Retrieving Data based DateandTime

### ISSUE THREAD

**Issue by AathifMahir** [zeshuaro/firestore_cache#36]
Love to see a new feature to firestore cache that retrieves data based on DateandTime of Original Documents

Example:
We have Product collection with all the documents has the Created and Updated DateandTime.

In that case, we'd love to retrieve new data from firestore whenever new documents added based Updated DateandTime.

Whenever new documents created or updated. The app need to get the new data by comparing the DateandTime last data arrived and new data DateandTime.

# **This would reduce the no of reads in firestore because this get's the newest added data to same database, all together the app has the latest data.**

**Comment by zeshuaro** [comment]
Isn't the package doing this already? You provide `cacheDocRef` and `firestoreCacheField` to give the updated datetime info.

**Comment by AathifMahir** [comment]
We can't give the timestep that's available in Product Collection in the current package instead we can give a different timestep by creating new document and collection that links directly this

**Comment by AathifMahir** [comment]
And also while refreshing the Data, Firestore cache retrives all the data from firestore right?

**Comment by zeshuaro** [comment]
> We can't give the timestep that's available in Collection of Document instead we can only reference to single document for cacheDocRef right? since we add timestep to all the documents in a collection, we can't reference that right

If you have a timestamp in each and every document and you want to use a caching strategy to retrieve the documents, I don't think there will be any advantages. In fact, it will be worse and may result in double the number of reads. 

Imagine you have a collection of documents where all the documents are outdated. When you're fetching all the documents, for each document, it will first check for its timestamp then fetch the document which cause two reads, whereas a normal fetch will just be one read for each document.

> And also while refreshing the Data, Firestore cache retrives all the data from firestore right? instead of new data only

Note that this package doesn't implement caching, it's just utilising the caching feature in `cloud_firestore`. So it really depends on how they're doing it.

**Comment by AathifMahir** [comment]
> > We can't give the timestep that's available in Collection of Document instead we can only reference to single document for cacheDocRef right? since we add timestep to all the documents in a collection, we can't reference that right
> 
> If you have a timestamp in each and every document and you want to use a caching strategy to retrieve the documents, I don't think there will be any advantages. In fact, it will be worse and may result in double the number of reads.
> 
> Imagine you have a collection of documents where all the documents are outdated. When you're fetching all the documents, for each document, it will first check for its timestamp then fetch the document which cause two reads, whereas a normal fetch will just be one read for each document.
> 
> > And also while refreshing the Data, Firestore cache retrives all the data from firestore right? instead of new data only
> 
> Note that this package doesn't implement caching, it's just utilising the caching feature in `cloud_firestore`. So it really depends on how they're doing it.

that's not how reading work instead, the new feature saves the last data update timestep in the sharedpreferences as variable, whenenver we update new data, the module would get all the data after that timestep. in that case we can expect over 50% less reads

**Comment by zeshuaro** [comment]
@AathifMahir I've read the article you shared and I think It's a good way of caching Firestore data. However, it involves manipulating the `Query` with additional ordering and filtering. I don't think that's a good idea for the package to manipulate the `Query` provided by the user as this may result in returning data that's different to the original `Query`. I think it's best for you to implement this caching strategy yourself if you want to use it.

**Comment by AathifMahir** [comment]
> @AathifMahir I've read the article you shared and I think It's a good way of caching Firestore data. However, it involves manipulating the `Query` with additional ordering and filtering. I don't think that's a good idea for the package to manipulate the `Query` provided by the user as this may result in returning data that's different to the original `Query`. I think it's best for you to implement this caching strategy yourself if you want to use it.

OK, I'll look for manual way of doing the caching that provided in the article. exactly i found a way to do so with this module. i'll write a article regarding that and share here. hope that helps many developers
