### ISSUE TITLE
Data Type Difference Between Document Snapshot and QuerySnapshot

### ISSUE THREAD

**Issue by AathifMahir** [zeshuaro/firestore_cache#52]
Since, the latest update Cloud Firestore, The Query and Dcoument Snapshots switched to <Map<String, dynamic>> data type from Object, But Firestore Cache Still using Object as Datatype for Query Snapshot, that causes conflicts between Document Snapshot and Query Snapshot.

![Screenshot 2021-06-04 225541](https://user-images.githubusercontent.com/17165402/120840921-7a1ee000-c588-11eb-94f2-b3c2c5cc9831.png)
![Screenshot 2021-06-04 225331](https://user-images.githubusercontent.com/17165402/120840929-7be8a380-c588-11eb-8e58-229f2a14d286.png)

Here's Image of Cloud Firestore's new Query Snapshot Data Type
![Screenshot 2021-06-04 230113](https://user-images.githubusercontent.com/17165402/120841234-e1d52b00-c588-11eb-98a1-d2f7ecb6c5eb.png)

**Comment by zeshuaro** [comment]
Thanks for reporting this issue, I have just released a new version to fix it 🙂
