### ISSUE TITLE
How handle deleted docs?

### ISSUE THREAD

**Issue by 3lB4rt0** [zeshuaro/firestore_cache#72]
Hi, in my app I am using the same approach as you to manage Firestore documents.
But then I dropped the cache method because I couldn't find a good solution to "what if the document was deleted from Firestore but still remains in the cache?"
Does your package solve this dilemma?

**Comment by zeshuaro** [comment]
Hi @3lB4rt0, this package relies on a timestamp field stored in Firestore to determine whether it should fetch from Firestore or the cache. So if you delete a document from Firestore and update the timestamp, it will know that the cache is outdated and will fetch from Firestore.
