### ISSUE TITLE
Support cloud_firestore: ^3.1.10

### ISSUE THREAD

**Issue by samatzhusup** [zeshuaro/firestore_cache#83]
Hi!
I'm showing incompatibility with  version 3.1.10

![2022-04-06_23-49-47](https://user-images.githubusercontent.com/50781959/162059171-f0e01460-ad66-48ee-a403-eecc69466d98.png)

**Comment by zeshuaro** [comment]
Hey @samatzhusup, thanks for raising this issue. Looking at your code, it seems like you might not have annotated the types correctly for your variables.

For example, `cacheDocRef` should be a type of `DocumentReference<Map<String, dynamic>>` and `users` should be `CollectionReference<Map<String, dynamic>>`.

Personally, I usually don't define the types myself unless I have to and let Dart figure out the types itself, e.g. I would just do `final cacheDocRef = FiresbaseFirestore.instance.doc('cache/books');`. Again, that's just my personal preference, but it would help you to get around issues like this.
